; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.30723.0 

	TITLE	C:\Users\Menyueru\Desktop\Barcamp2014\Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
